# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=63)),
                ('date', models.DateTimeField(auto_now=True, db_index=True)),
                ('text', models.TextField()),
            ],
        ),
    ]
